# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='aa@qq.comd', max_length=32, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='123', max_length=32, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType', verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Role', verbose_name='角色表'),
        ),
    ]
